limit.maxIDLength:
  - value: 255
    constraints: {}
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
    constraints: {}
limit.searchAttributesNumberOfKeywords:
  - value: 50
    constraints: {}
limit.searchAttributesNumberOfText:
  - value: 50
    constraints: {}
limit.searchAttributesNumberOfInt:
  - value: 50
    constraints: {}
limit.searchAttributesNumberOfDouble:
  - value: 50
    constraints: {}
limit.searchAttributesNumberOfBool:
  - value: 50
    constraints: {}
limit.searchAttributesNumberOfDatetime:
  - value: 50
    constraints: {}
limit.searchAttributesSizeOfValue:
  - value: 8192
    constraints: {}
limit.searchAttributesTotalSize:
  - value: 409600
    constraints: {}
limit.maxSearchAttributesCount:
  - value: 200
    constraints: {}
frontend.enableUpdateWorkflowExecution:
  - value: true
    constraints: {}
